stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cystack-deployer
  tags:
    - cs_newgen
  only:
    - main
    - tags

deploy:
  stage: deploy
  script:
    - cystack-deployer
  tags:
    - cs_newgen
  only:
    - main
    - tags
